---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.1.0"
    hooks:
      - id: "check-case-conflict"
      - id: "check-xml"
      - id: "double-quote-string-fixer"
      - id: "trailing-whitespace"
      - id: "flake8"
  - repo: "https://github.com/prettier/prettier"
    rev: "1.16.4"
    hooks:
      - id: "prettier"
